name: Release Watcher

on:
  
  #   branches:
  #     - main
  schedule:
    - cron: '0 9 * * 1'  # Every Monday at 9 AM UTC
  workflow_dispatch:    # Allows manual triggering

jobs:
  watch:
    runs-on: ubuntu-latest
    steps:
      - name: Print event name 
        run:  |
          echo "Event triggered by: ${{ github.event_name }}"
      
      - name: Print current date and time
        run: |
          echo "Current Date and Time: $(date)"
      
      - name: Release watch complete
        run: echo "Release watch complete"



